version: '3.9'
services:
    app:
        image: train-ticket-image
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:9191"
        links:
            - db
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=Password
        ports:
            - '13306:3306'
